export const ELITE_MODIFIERS = {
    health: 1.8,
    speed: 1.3,
    damage: 1.25,
};

export const ENEMIES = {
    drifter: {
        type: "drifter",
        name: "Drifter",
        health: 28,
        speed: 115,
        radius: 10,
        contactDamage: 1,
        xp: 10,
        eliteBehavior: "burst",
    },
    watcher: {
        type: "watcher",
        name: "Watcher",
        health: 45,
        speed: 75,
        radius: 10,
        contactDamage: 1,
        xp: 25,
        bulletDamage: 1,
        bulletSpeed: 165,
        fireCooldownTicks: 90,
        eliteBehavior: "rapid-fire",
    },
    mass: {
        type: "mass",
        name: "Mass",
        health: 110,
        speed: 50,
        radius: 11,
        contactDamage: 2,
        xp: 50,
        bulletDamage: 1,
        bulletSpeed: 125,
        fireCooldownTicks: 144,
        eliteBehavior: "burst-death",
    },
    phantom: {
        type: "phantom",
        name: "Phantom",
        health: 24,
        speed: 95,
        radius: 10,
        contactDamage: 1,
        xp: 20,
        eliteBehavior: "burst",
    },
    orbiter: {
        type: "orbiter",
        name: "Orbiter",
        health: 36,
        speed: 135,
        radius: 10,
        contactDamage: 1,
        xp: 30,
        bulletDamage: 1,
        bulletSpeed: 150,
        fireCooldownTicks: 114,
        eliteBehavior: "rapid-fire",
    },
    splitter: {
        type: "splitter",
        name: "Splitter",
        health: 65,
        speed: 65,
        radius: 11,
        contactDamage: 1,
        xp: 35,
        eliteBehavior: "death-explosion",
    },
};
